#!/usr/bin/env python3
from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from car_control_modular.config_loader import load_config_to_env


EXPECTED = {
    "VISION_ENGINE": "rknn",
    "VISION_MODEL_PATH": "models/yolo11n_int8_person_val2017.rknn",
    "VISION_REID_ENABLE": "1",
    "VISION_REID_MODEL_PATH": "models/osnet_x0_25_msmt17_b1.rknn",
    "RKNN_REID_INPUT_WIDTH": "128",
    "RKNN_REID_INPUT_HEIGHT": "256",
    "RKNN_REID_INPUT_FORMAT": "RGB",
    "RKNN_CAMERA_CAPTURE_MODE": "gstreamer_mjpeg",
    "RKNN_CAMERA_DEVICE": "/dev/video1",
    "RKNN_CAMERA_FOURCC": "MJPG",
    "RKNN_CAMERA_LATEST_DRAIN_MAX": "8",
    "RKNN_YOLO_INPUT_SIZE": "640",
    "IR_BACKEND": "iio",
    "IR_TRIGGER_VALUE": "0",
    "IR_IIO_RIGHT_DEVICE": "4",
    "IR_IIO_LEFT_DEVICE": "3",
    "IR_IIO_FRONT_DEVICE": "5",
    "MODULE_MMWAVE_ENABLE": "1",
    "MODULE_IMU_ENABLE": "1",
    "MMWAVE_BACKEND": "at2410",
    "MMWAVE_AT2410_PORT": "/dev/serial/by-id/usb-SIPEED_UARTx4_HS_FactoryAIOT_Prog_Serial-if00",
    "MMWAVE_AT2410_BAUDRATE": "9600",
    "MMWAVE_AT2410_READ_TIMEOUT_SEC": "0.04",
    "MMWAVE_AT2410_VERIFY_ON_INIT": "0",
    "MMWAVE_TARGET_LIMIT": "3",
    "MMWAVE_TARGET_MODE": "angle",
    "MMWAVE_FRONT_ANGLE_DEG": "60",
    "MMWAVE_DISTANCE_BIAS_M": "0.0",
    "MMWAVE_MIN_DISTANCE_M": "0.50",
    "MMWAVE_MAX_DISTANCE_M": "10.0",
    "MMWAVE_ASYNC_CACHE_ENABLE": "1",
    "MMWAVE_CACHE_INTERVAL_SEC": "0.04",
    "MMWAVE_CACHE_WINDOW_SEC": "0.80",
    "MODULE_ULTRASONIC_ENABLE": "1",
    "DISTANCE_SOURCE": "vision_mmwave",
    "ULTRASONIC_BACKEND": "iio",
    "ULTRASONIC_IIO_DEVICE": "2",
    "ULTRASONIC_IIO_DEVICE_NAME": "hcsr04",
    "ULTRASONIC_FILTER_WINDOW": "3",
    "ULTRASONIC_TARGET_CONFIRM_FRAMES": "2",
    "ULTRASONIC_BRAKE_CONFIRM_FRAMES": "2",
    "ULTRASONIC_HYSTERESIS_M": "0.25",
    "ULTRASONIC_IMMEDIATE_BRAKE_M": "0.35",
    "IMU_BACKEND": "icm20600",
    "IMU_FAIL_SOFT": "1",
    "IMU_ENABLE_ON_INIT": "1",
    "IMU_DISABLE_ON_DEINIT": "0",
    "IMU_LOG_ENABLE": "1",
    "IMU_LOG_EVERY_SEC": "0.50",
    "IMU_ACCEL_NAME": "gsensor",
    "IMU_GYRO_NAME": "gyro",
    "IMU_ACCEL_MISC_DEV": "/dev/mma8452_daemon",
    "IMU_GYRO_MISC_DEV": "/dev/gyrosensor",
    "IMU_ACCEL_RATE_MS": "30",
    "IMU_GYRO_RATE_MS": "30",
    "IMU_ACCEL_LSB_PER_G": "16384.0",
    "IMU_GYRO_LSB_PER_DPS": "16.4",
    "MOTOR_BACKEND": "rs485_lz30ema",
    "MOTOR_PERCENT_LIMIT": "100",
    "MOTOR_RS485_BAUDRATE": "115200",
    "MOTOR_RS485_TIMEOUT": "0.15",
    "MOTOR_FORWARD_RAW_TARGET": "0",
    "MOTOR_STEER_RAW_TARGET": "0",
    "MOTOR_ROTATE_RAW_TARGET": "30",
    "MOTOR_FORWARD_TARGET_SIGN": "-1",
    "MOTOR_EXIT_PARKING_MODE_ON_ARM": "0",
    "MOTOR_RS485_STOP_ZERO_DELAY_SEC": "0",
    "MOTOR_RS485_TRANSITION_STOP_MODE": "emergency",
    "MOTOR_RS485_TRANSITION_STOP_DELAY_SEC": "0",
    "MOTOR_RS485_TRANSITION_STOP_REPEAT": "0",
    "MOTOR_RS485_TARGET_MIN_INTERVAL_SEC": "0.10",
    "MOTOR_FORWARD_LIKE_KEEPALIVE_SEC": "1.0",
    "BRAKE_HOLD_REFRESH_INTERVAL_SEC": "1.2",
    "MAX_FORWARD_PERCENT": "72",
    "STEER_PERCENT_LIMIT": "88",
    "FORWARD_SPEED_FAR_PERCENT": "55",
    "FOLLOW_SEARCH_BEFORE_FIRST_PERSON": "0",
    "FOLLOW_STARTUP_SEARCH_DELAY_SEC": "0.0",
    "FOLLOW_SEARCH_TIMEOUT_SEC": "4.0",
    "FOLLOW_INITIAL_TARGET_CONFIRM_FRAMES": "3",
    "FOLLOW_LOST_CONFIRM_SEC": "15",
    "FOLLOW_LOST_CONFIRM_FRAMES": "5",
    "FOLLOW_RELEASE_TARGET_ON_LOST": "0",
    "FOLLOW_STEER_ENTER_LEFT_RATIO": "0.25",
    "FOLLOW_STEER_ENTER_RIGHT_RATIO": "0.75",
    "FOLLOW_STEER_RELEASE_LEFT_RATIO": "0.35",
    "FOLLOW_STEER_RELEASE_RIGHT_RATIO": "0.65",
    "SEARCH_ROTATE_FRONT_BLOCK_ENABLE": "0",
    "SEARCH_ROTATE_DISTANCE_BLOCK_ENABLE": "1",
    "BLOCKED_TURN_FORWARD_ENABLE": "1",
    "BLOCKED_TURN_FORWARD_MAX_STEPS": "2",
    "DIRECT_STOP_REPEAT_INTERVAL_SEC": "0.75",
    "ROTATE_DURATION": "1.2",
    "ROTATE_PULSE_BRAKE_ENABLE": "1",
    "ROTATE_PULSE_PAUSE_SEC": "0.01",
    "ROTATE_HOLD_STALE_SEC": "0.02",
    "ROTATE_TURN_PERCENT_FROM_FORWARD": "20",
    "ROTATE_TURN_PERCENT_CHAIN": "30",
    "ROTATE_RAW_TARGET_VISIBLE": "30",
    "ROTATE_RAW_TARGET_LOST_WAIT": "30",
    "ROTATE_RAW_TARGET_SEARCH": "30",
    "VISION_MMWAVE_ANGLE_SIGN": "1.0",
    "VISION_MMWAVE_ANGLE_TIE_MARGIN_DEG": "2.0",
    "VISION_MMWAVE_DISTANCE_BIAS_M": "0.0",
    "VISION_MMWAVE_MIN_DISTANCE_M": "0.50",
    "VISION_MMWAVE_MAX_DISTANCE_M": "10.0",
    "VISION_MMWAVE_LATENCY_SEC": "0.13",
    "VISION_MMWAVE_CACHE_MAX_AGE_SEC": "0.20",
    "VISION_MMWAVE_USE_ASYNC_CACHE": "1",
    "VISION_CONTROL_USE_PREDICTED_TRACKS": "0",
    "Y8_DEEPSORT_MAX_OUTPUT_AGE": "0",
    "Y8_IDENTITY_BANK_ENABLE": "1",
    "Y8_IDENTITY_MATCH_THRESHOLD": "0.32",
    "Y8_IDENTITY_UPDATE_THRESHOLD": "0.30",
    "Y8_IDENTITY_UPDATE_INTERVAL": "5",
    "Y8_IDENTITY_MAX_AREA_RATIO": "0.75",
    "Y8_IDENTITY_MAX_WIDTH_RATIO": "0.85",
    "Y8_IDENTITY_MAX_ASPECT_RATIO": "1.45",
    "Y8_IDENTITY_MAX_EDGE_TOUCH_COUNT": "2",
    "Y8_IDENTITY_REACQUIRE_THRESHOLD": "0.50",
    "Y8_IDENTITY_REACQUIRE_MAX_FRAMES": "90",
    "Y8_IDENTITY_REACQUIRE_MULTI_CANDIDATE_ENABLE": "1",
    "Y8_IDENTITY_REACQUIRE_MULTI_CANDIDATE_THRESHOLD": "0.40",
    "Y8_IDENTITY_REACQUIRE_MULTI_CANDIDATE_MARGIN": "0.12",
    "Y8_IDENTITY_NEW_CONFIRM_FRAMES": "2",
    "Y8_IDENTITY_MAPPED_VERIFY_ENABLE": "1",
    "Y8_IDENTITY_MAPPED_VERIFY_THRESHOLD": "0.40",
    "Y8_IDENTITY_MAPPED_BAD_QUALITY_RETURNS_UNASSIGNED": "0",
    "Y8_IDENTITY_EXCLUSIVE_UID_CLAIM_ENABLE": "1",
    "Y8_IDENTITY_EXCLUSIVE_UID_CLAIM_FRAMES": "15",
    "Y8_IDENTITY_CONTROLLED_HANDOFF_ENABLE": "1",
    "Y8_IDENTITY_CONTROLLED_HANDOFF_CONFIRM_FRAMES": "3",
    "Y8_IDENTITY_CONTROLLED_HANDOFF_THRESHOLD": "0.30",
    "Y8_IDENTITY_CONTROLLED_HANDOFF_MIN_OLD_TRACK_GAP_FRAMES": "2",
    "Y8_IDENTITY_SUPPRESS_DUPLICATE_UIDS": "1",
    "Y8_PREDICTED_REID_VERIFY_ENABLE": "0",
    "Y8_PREDICTED_REID_VERIFY_THRESHOLD": "0.30",
    "TRACK_MEMORY_ENABLED": "0",
    "TRACK_MEMORY_REACQUIRE_BY_GEOMETRY": "1",
    "TRACK_MEMORY_REACQUIRE_CONFIRM_FRAMES": "2",
}


def main() -> int:
    config_path = Path(sys.argv[1]) if len(sys.argv) >= 2 else ROOT / "car_control_modular/config/reid_runtime.ini"
    loaded = load_config_to_env(str(config_path))
    if loaded is None:
        raise AssertionError(f"failed to load config: {config_path}")

    failures = []
    for key, expected in EXPECTED.items():
        actual = os.environ.get(key)
        print(f"{key}={actual}")
        if actual != expected:
            failures.append(f"{key}: expected {expected!r}, got {actual!r}")

    if failures:
        raise AssertionError("; ".join(failures))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
