[modules]
# 视觉主要是人
vision = true
# 红外数据
ir = true
# 毫米波数据
mmwave = true
# 超声数据
ultrasonic = false
# 沙坑
bunker = true

[vision]
model_path = ./merged_person_bunker.cvimodel
person_class_id = 0
confidence_threshold = 0.25
target_select = largest_area

[distance]
source = mmwave
target_distance_m = 1.0
brake_distance_m = 0.5
mmwave_obstacle_threshold_m = 1.0

[motion]
min_forward_percent = 10
max_forward_percent = 100
rotate_duration = 0.15
brake_hold_refresh_sec = 0.10

[bunker]
# off(关闭), split(分开的模型), merge(共用一个模型)
mode = merged
class_ids = 1,2
class_names = 1:bunker,2:pond
score_threshold = 0.0
area_ratio_stop = 0.05

