[modules]
# 视觉主要是人
vision = true
# 红外
ir = true
# 毫米波数据
mmwave = true
# 超声数据
ultrasonic = false
# 沙坑
bunker = true

[vision]
model_path = ../../../tdl_models/cv181x/yolov8s_det_coco80_640_640_INT8_cv181x.cvimodel
person_class_id = 0
confidence_threshold = 0.25
target_select = largest_area

[distance]
source = mmwave
target_distance_m = 1.0
brake_distance_m = 0.5
mmwave_obstacle_threshold_m = 1.0

[motion]
min_forward_percent = 10
max_forward_percent = 100
rotate_duration = 0.15
brake_hold_refresh_sec = 0.10

[bunker]
# off(关闭), split(分开的模型), merge(共用一个模型)
mode = split
workdir = ./yolov8-track
model_path = ./yolov8-track/shakeng_yolov8n_cv181x_int8_640_compat12.cvimodel
class_ids = 0,1
class_names = 0:bunker,1:pond
score_threshold = 0.0
area_ratio_stop = 0.2
sample_det_conf = 0.75
get_frame_timeout_ms = 200
loop_period_ms = 100
active_hold_sec = 0.35
stop_consec_frames = 2
echo_raw = false
sample_binary = ./sample_personv8_track

