[modules]
# 视觉主要是人
vision = true
# 红外
ir = true
# 毫米波
mmwave = false
# 超声
ultrasonic = true
# 沙坑
bunker = false

[vision]
model_path = ../../../tdl_models/cv181x/yolov8s_det_coco80_640_640_INT8_cv181x.cvimodel
person_class_id = 0
confidence_threshold = 0.25
target_select = largest_area

[distance]
source = ultrasonic
target_distance_m = 1.0
brake_distance_m = 0.5
mmwave_obstacle_threshold_m = 1.0

[motion]
min_forward_percent = 10
max_forward_percent = 100
rotate_duration = 0.15
brake_hold_refresh_sec = 0.10

[bunker]
# off(关闭), split(分开的模型), merge(共用一个模型)
mode = off
